app1/urls.py
from django.urls import path
from app1.views import *
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('', inicio, name="Inicio"),
    path('vuelo/', vuelo),
    path('personal/', personal),
    path('pasajero/', pasajero),
    path('sobrenostros', sobrenosotros, name="Sobrenosotros"),

#URL DE CREACION
    path('formulario1/', formulariovuelo, name="Crear Vuelos"),
    path('formulario2/', formulariopersonal, name="Crear Personal"),
    path('formulario3/', formulariopasajero, name="Crear Pasajeros"),

#URL DE LEER
    path('leerVuelos/',leerVuelos, name="Leer Vuelos"),
    path('leerPersonal/',leerPersonal, name="Leer Personal"),
    path('leerPasajeros/',leerPasajero, name="Leer Pasajeros"),

#URL DE EDICION
    path('editaVuelo/<numVuelo>/', editaVuelo, name = "EditaVuelo"),
    path('editarPersonal/<profesionPersonal>/', editarPersonal, name = "EditarPersonal"),
    path('editarPasajero/<idvueloPasajero>/', editarPasajero, name = "EditarPasajero"),

#URL DE ELIMINACION
    path('eliminaVuelo/<numVuelo>/', eliminaVuelo, name = "EliminaVuelo"),
    path('eliminaPersonal/<profesionPersonal>/', eliminaPersonal, name = "EliminaPersonal"),
    path('eliminaPasajero/<idvueloPasajero>/', eliminaPasajero, name = "EliminaPasajero"),

#URL DE BUSQUEDAS
    path('bus/', bus, name="Buscar"),
    path('buscarVuelos/', busquedaVuelos, name="Buscar Vuelos"),
    path('buscarPersonal/', busquedaPersonal, name="Buscar Personal"),
    path('buscarPasajero/', busquedaPasajero, name="Buscar Pasajeros"),
##
    path('buscar_pasa/',buscar_pasa),
    path('buscar_per/',buscar_per),
    path('buscar/',buscar),

#URL DE LOGIN Y LOGOUT
    path('login/',InicioSesion, name="Login"),
    path('registro/',registro, name="Registrarse"),
    path('logout/', LogoutView.as_view(template_name="app1/logout.html"), name="Logout"),

#URL DE EDICIONUSUARIO
    path('editUser/',editarUsuario, name="Editar Usuario"),
    path('avatar/', agregarAvatar, name="Avatar"),

    ]

proyecto_i/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include("app1.urls"))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app1/models.py
from distutils.command.upload import upload
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Vuelo(models.Model):
    def __str__(self):
        return f'Vuelo: {self.id_vuelo} ----- sale el: {self.fecha}'
    id_vuelo = models.IntegerField()
    salida = models.CharField(max_length=50)
    destino = models.CharField(max_length=50)
    fecha = models.DateField()    #2022-05-23(AAAA-MM-DD)
    hora_de_salida = models.TimeField() #02:13(HH:MM)

class Personal(models.Model):
    def __str__(self):
        return f'Personal: {self.profesion} ----- del vuelo: {self.id_vuelo}'
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    profesion = models.CharField(max_length=50)
    id_vuelo = models.IntegerField()

class Pasajero(models.Model):
    def __str__(self):
        return f'Pasajero: {self.nombre} {self.apellido}------ DNI:{self.documento}' 
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    documento = models.IntegerField()
    id_vuelo = models.IntegerField()


class Avatar(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="avatares", null=True, blank=True)

app1/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from app1.models import Avatar


class FormuVuelo(forms.Form):
    id_vuelo = forms.IntegerField()
    salida = forms.CharField(max_length=50)
    destino = forms.CharField(max_length=50)
    fecha = forms.DateField()    #2022-05-23(AAAA-MM-DD)
    hora_de_salida = forms.TimeField() #02:13(HH:MM)


class FormuPersonal(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellido = forms.CharField(max_length=50)
    profesion = forms.CharField(max_length=50)
    id_vuelo = forms.IntegerField()

class FormuPasajero(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellido = forms.CharField(max_length=50)
    documento = forms.IntegerField()
    id_vuelo = forms.IntegerField()

class FormularioRegistro(UserCreationForm):
    email = forms.EmailField(label='Ingrese email')
    first_name= forms.CharField(label='Ingrese nombre')
    last_name= forms.CharField(label='Ingrese apellido')
    password1 = forms.CharField(label='Ingrese la contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repita la contraseña', widget=forms.PasswordInput)

    class Meta:

        model = User
        fields = ["username","first_name","last_name","email","password1","password2"]

class FormularioEditarUsuario(UserCreationForm):
    email = forms.EmailField(label='Ingrese email')
    first_name= forms.CharField(label='Ingrese nombre')
    last_name= forms.CharField(label='Ingrese apellido')
    password1 = forms.CharField(label='Ingrese la contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repita la contraseña', widget=forms.PasswordInput)

    class Meta:

        model = User
        fields = ["first_name","last_name","email","password1","password2"]

class FormuAvatar(forms.ModelForm):

    class Meta:

        model = Avatar
        fields = ["imagen"]

app1/views.py
from unicodedata import decomposition
from django.shortcuts import render
from django.http import HttpResponse

from app1.models import *
from app1.forms import *

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm #se importa el AuthenticationForm para el inicio de sesion
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required


# Create your views here.

############
#  INICIO  #
############

def inicio(request):
    return render(request,'app1/inicio.html')


############
#  LOGIN  #
############

def InicioSesion(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data = request.POST)
        if form.is_valid():
            usuario = form.cleaned_data.get("username")
            contra = form.cleaned_data.get("password")
            user = authenticate(username = usuario, password = contra)
            if user:
                login(request, user)
                return render(request, "app1/inicio.html", {"mensaje":f"Bienvenido/a {user}"})
        else:
            return render(request, "app1/inicio.html", {"mensaje": "Datos incorrectos"})
    else:
        form = AuthenticationForm()
    return render(request, "app1/login.html", {"f1":form})


def registro(request):
    if request.method == "POST":
        formu = FormularioRegistro(request.POST)
        if formu.is_valid():
            username = formu.cleaned_data["username"]
            formu.save()
            return render(request, "app1/inicio.html", {"mensaje": f"Usuario {username} creado."})
    else:
        formu = FormularioRegistro()
    return render(request, "app1/registro.html", {"f2":formu})



############
#  VUELOS  #
############

@login_required
def vuelo(request):
    return render(request,'app1/vuelo.html')


#CREACION DE VUELOS
@login_required
def formulariovuelo(request):
    if request.method=="POST":#si yo le doy al boton GO
        formulariovuelo = FormuVuelo(request.POST)
        if formulariovuelo.is_valid():
            info = formulariovuelo.cleaned_data
            vuelof = Vuelo(id_vuelo = info["id_vuelo"], salida = info["salida"], destino = info["destino"], fecha = info["fecha"], hora_de_salida = info["hora_de_salida"])#lee la informacion de las cajas de texto
            vuelof.save()#guardar en la base de datos
            return render(request,"app1/inicio.html")#despues de enviar salta esta pagina
    else:
        formulariovuelo = FormuVuelo()
    return render(request,"app1/FVuelo.html",{"formulario1":formulariovuelo})#cuando entro a la pagina web por primera vez sale este return


#BUSQUEDA DE VUELOS
@login_required
def busquedaVuelos(request):
    return render(request,"app1/busquedaVuelos.html")


@login_required
def buscar(request):
    if request.GET["salida"]:
        busqueda = request.GET["salida"]
        vuelos = Vuelo.objects.filter(salida=busqueda)#puede ir tambien camada__icontains = busqueda
        return render(request,"app1/vuelo_b.html",{"vuelos":vuelos, "busqueda":busqueda})
    else:
        mensaje="No enviaste datos."
    return HttpResponse(f"Estoy buscando el vuelo que sale de: {busqueda}")


@login_required
#LEER VUELOS
def leerVuelos(request):
    fly = Vuelo.objects.all()
    contexto = {"fly":fly}
    return render(request,"app1/vuelo.html",contexto)


@login_required
#ELIMINAR VUELOS
def eliminaVuelo(request, numVuelo):
    idvuelo= Vuelo.objects.get(id_vuelo=numVuelo)
    idvuelo.delete()
    vuelos = Vuelo.objects.all()
    contextov = {"fly":vuelos}
    return render (request, "App1/vuelo.html", contextov)


#EDITAR VUELOS
@login_required
def editaVuelo(request, numVuelo):
    idvuelo = Vuelo.objects.get(id_vuelo=numVuelo)

    if request.method == "POST":
        formulariovuelo = FormuVuelo(request.POST)
        if formulariovuelo.is_valid():
            
            info = formulariovuelo.cleaned_data
            
            idvuelo.id_vuelo = info["id_vuelo"]
            idvuelo.salida = info["salida"]
            idvuelo.destino = info["destino"]
            idvuelo.fecha = info["fecha"]
            idvuelo.hora_de_salida = info["hora_de_salida"]

            idvuelo.save()
            return render(request,"app1/inicio.html")
    else:
        formulariovuelo = FormuVuelo(initial={"id_vuelo":idvuelo.id_vuelo,"salida":idvuelo.salida,
        "destino": idvuelo.destino, "fecha": idvuelo.fecha, "hora_de_salida": idvuelo.hora_de_salida })
    return render(request,"app1/editarVuelo.html", {"formulario1":formulariovuelo, "idVuelo": numVuelo})


############
# PERSONAL #
############

@login_required
def personal(request):
    return render(request,'app1/personal.html')


@login_required
#CREACION DE PERSONAL
def formulariopersonal(request):
    if request.method=="POST":
        formulariopersonal = FormuPersonal(request.POST)
        if formulariopersonal.is_valid():
            info = formulariopersonal.cleaned_data
            personalf = Personal(nombre = info["nombre"], apellido = info["apellido"], profesion = info["profesion"],  id_vuelo = info["id_vuelo"])
            personalf.save()
            return render(request,"app1/inicio.html")
    else:
        formulariopersonal = FormuPersonal()
    return render(request,"app1/FPersonal.html",{"formulario2":formulariopersonal})


@login_required
#BUSQUEDA DE PERSONAL
def busquedaPersonal(request):
    return render(request,"app1/busquedaPersonal.html")


@login_required
def buscar_per(request):
    if request.GET["profesion"]:
        busqueda_per = request.GET["profesion"]
        personas = Personal.objects.filter(profesion = busqueda_per)
        return render(request,"app1/personal_b.html",{"personas":personas, "busqueda_per":busqueda_per})
    else:
        mensaje="No enviaste datos."
    return HttpResponse(f"Estoy buscando la profesión: {busqueda_per}")


@login_required
#LEER PERSONAL
def leerPersonal(request):
    persona = Personal.objects.all()
    contexto = {"persona":persona}
    return render(request,"app1/personal.html",contexto)


@login_required
#ELIMINAR PERSONAL
def eliminaPersonal(request, profesionPersonal):
    profesionPe= Personal.objects.get(profesion=profesionPersonal)
    profesionPe.delete()
    personalElim = Personal.objects.all()
    contextoPe = {"persona":personalElim}
    return render (request, "App1/personal.html", contextoPe)


@login_required
#EDITAR PERSONAL
def editarPersonal(request, profesionPersonal):
    profesion= Personal.objects.get(profesion=profesionPersonal)

    if request.method=="POST":
        formulariopersonal = FormuPersonal(request.POST)
        if formulariopersonal.is_valid():
            
            info = formulariopersonal.cleaned_data
           
            profesion.nombre = info["nombre"]
            profesion.apellido = info["apellido"]
            profesion.profesion = info["profesion"]
            profesion.id_vuelo = info["id_vuelo"]

            profesion.save()
            return render(request,"app1/inicio.html")
    else:
        formulariopersonal = FormuPersonal(initial={"nombre":profesion.nombre,"apellido":profesion.apellido,
        "profesion":profesion.profesion, "id_vuelo":profesion.id_vuelo})
    return render(request,"app1/editarPersonal.html",{"formulario2":formulariopersonal, "profesionPersonal": profesionPersonal })  




############
# PASAJERO #
############

@login_required
def pasajero(request):
    return render(request,'app1/pasajero.html')


@login_required
# CREACION DE PASAJERO
def formulariopasajero(request):
    if request.method=="POST":
        formulariopasajero = FormuPasajero(request.POST)
        if formulariopasajero.is_valid():
            info = formulariopasajero.cleaned_data
            editPersonal = Pasajero(nombre = info["nombre"], apellido = info["apellido"], documento = info["documento"], id_vuelo = info["id_vuelo"])
            editPersonal.save()
            return render(request,"app1/inicio.html")
    else:
        formulariopasajero = FormuPasajero()
    return render(request,"app1/FPasajero.html",{"formulario3":formulariopasajero})


@login_required
#BUSQUEDA DE PASAJERO
def busquedaPasajero(request):
    return render(request,"app1/busquedaPasajero.html")

@login_required
def buscar_pasa(request):
    if request.GET["id_vuelo"]:
        busqueda_pasa = request.GET["id_vuelo"]
        pasajeros = Pasajero.objects.filter(id_vuelo = busqueda_pasa)
        return render(request,"app1/pasajero_b.html",{"pasajeros":pasajeros, "busqueda_pasa":busqueda_pasa})
    else:
        mensaje="No enviaste datos."
    return HttpResponse(f"Estoy buscando los pasajeros del vuelo: {busqueda_pasa}")

@login_required
#LEER PASAJERO
def leerPasajero(request):
    pasa = Pasajero.objects.all()
    contexto = {"pasa":pasa}
    return render(request,"app1/pasajero.html",contexto)  


@login_required
#ELIMINAR PASAJERO
def eliminaPasajero(request, idvueloPasajero):
    elimPasajero= Pasajero.objects.get(id_vuelo=idvueloPasajero)
    elimPasajero.delete()

    pasajeroElim = Pasajero.objects.all()
    contextoPa = {"pasa":pasajeroElim}
    return render (request, "App1/pasajero.html", contextoPa)


@login_required
#EDITAR PASAJERO
def editarPasajero(request, idvueloPasajero):
    editPasajero= Pasajero.objects.get(id_vuelo=idvueloPasajero)
    if request.method=="POST":
        
        formulariopasajero = FormuPasajero(request.POST)
        
        if formulariopasajero.is_valid():
            info = formulariopasajero.cleaned_data

            editPasajero.nombre = info["nombre"]
            editPasajero.apellido = info["apellido"]
            editPasajero.documento = info["documento"]
            editPasajero.id_vuelo = info["id_vuelo"]

            editPasajero.save()
            return render(request,"app1/inicio.html")
    else:
        formulariopasajero = FormuPasajero(initial={"nombre": editPasajero.nombre, "apellido": editPasajero.apellido,

app1/templates/app1/FPersonal.html
{% extends "app1/padre2.html" %}



{% block titulo %}

<h1>En esta seccion agregue los datos del personal</h1>



<form action = "" method="POST"> {% csrf_token %}
            
    <table align="center">
        <p>

            <div>

                <h6>Ingrese datos del personal</h6>
                    
                {{formulario2.as_table}}

            </div>
            
        </p>
    </table>

                    
    <input type="submit" value="ENVIAR">
                    
</form>
  

{% endblock %}

app1/templates/app1/buscar.html
{% extends "app1/padre2.html" %}



{% block titulo %}

<div>
    
    <h1 style="color:rgb(0, 9, 4) ;">
        Ingrese lo que desea buscar:                  
    </h1>
    

    <button style="background-color:black; border-color: forestgreen">
        <a href="{% url 'Buscar Vuelos' %}">Buscar Vuelos</a>
    </button>
    <button style="background-color:black; border-color: forestgreen">
        <a href="{% url 'Buscar Personal' %}">Buscar Personal</a>
    </button>
    <button style="background-color:black; border-color: forestgreen">
        <a href="{% url 'Buscar Pasajeros' %}">Buscar Pasajeros</a>
    </button>
    
</div>

{% endblock %}

app1/templates/app1/busquedaPasajero.html
{% extends "app1/padre2.html" %}



{% block titulo %}

<h1>En esta seccion vamos a buscar los pasajeros por su numero de vuelo</h1>



<form action="/app1/buscar_pasa" method="GET">
    <p>
        <div>

            <h6>Ingrese numero de vuelo</h6>
            
            <input type="number" name="id_vuelo" id="id_vuelo">

            <input type="submit" value="Buscar">
        </div>
        
    </p>
</form>

{% endblock %}

app1/templates/app1/busquedaPersonal.html
{% extends "app1/padre2.html" %}



{% block titulo %}

<h1>En esta seccion vamos a buscar al personal por su profesión</h1>


<form action="/app1/buscar_per" method="GET">
    <p>
        <div>

            <h6>Ingrese aquí la profesion</h6>

            <input type="text" name="profesion" id="profesion">
        
            <input type="submit" value="Buscar">

        </div>
    
    </p>
</form>

{% endblock %}

app1/templates/app1/busquedaVuelos.html
{% extends "app1/padre2.html" %}



{% block titulo %}

<h1>En esta seccion vamos a buscar vuelos por su salida</h1>



<form action="/app1/buscar" method="GET">
    <p>
        <div>

        <h6>Ingrese aqui la salida</h6>

        <input type="text" name="salida" id="salida">

        <input type="submit" value="Buscar">

        </div>
    
    </p>
</form>

{% endblock %}

app1/templates/app1/editarPersonal.html
{% extends "app1/padre2.html" %}



{% block titulo %}

<h3>
    <p>Edite datos del personal</p>
</h3>

{% endblock %}


{% block descripcion %}

<form action = "" method="POST"> {% csrf_token %}
            
    <table align="center">
        <p>

            <div>
                    
                {{formulario2.as_table}}

            </div>
            
        </p>
    </table>

                    
    <input type="submit" value="ENVIAR">
                    
</form> 

{% endblock %}

app1/templates/app1/editarVuelo.html
{% extends "app1/padre2.html" %}



{% block titulo %}
<h3>
    <p>Edite datos del vuelo</p>
</h3>

{% endblock %}


{% block descripcion %}


<form action = "" method="POST"> {% csrf_token %}
            
    <table align="center">
        <p>
            <div>
                <h6>La fecha ingrese como (AAAA-MM-DD)(2021-03-13)</h6>
                <h6>La hora ingrese como (HH:MM)(02:15)</h6>
                {{formulario1.as_table}}
            </div>
        </p>
    </table>

                    
    <input type="submit" value="ENVIAR">

{% endblock %}



app1/templates/app1/inicio.html
{% extends "app1/padre.html" %}



{% block descripcion %}
<h2 style="color: rgb(0, 0, 0) ;">
    <p>
        {{mensaje}}
    </p>
    Pagina de información de Vuelos

</h2>
{% endblock %}

app1/templates/app1/login.html
{% extends "app1/padre.html" %}


{% block titulo %}
<h1 style="color:white">
    Inicio de sesión
</h1>
{% endblock %}



{% block descripcion %}

<form action=""method="POST">{% csrf_token %}

    <h6 style="color:white;">
        {{f1.as_p}}
    </h6>
    
    <button type="submit">Iniciar sesion</button>



</form>

{% endblock %}

app1/templates/app1/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Vuelos</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'app1/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'app1/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">

                {% if request.user.is_authenticated %}

                <a class="navbar-brand" href="{% url 'Editar Usuario' %}">Editar Usuario</a>
                <a class="navbar-brand" href="{% url 'Logout' %}">Cerrar sesión</a>
                <a class="navbar-brand" href="{% url 'Avatar' %}">Avatar</a>

                <a class="navbar-brand">{{user.username}}</a>

                {% with user.avatar_set.first as miAvatar %}

                {% if miAvatar %}

                <img src="{{miAvatar.imagen.url}}" alt="no encontro la imagen" style="max-width: 50px;">

                {% endif %}

                {% endwith %}

                {% else %}

                <a class="navbar-brand" href="{% url 'Registrarse' %}">Registrarse</a>
                <a class="navbar-brand" href="{% url 'Login' %}">Iniciar sesión</a>
            

                {% endif %}

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'Leer Vuelos' %}">Vuelos</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Leer Personal' %}">Personal</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Leer Pasajeros' %}">Pasajeros</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Buscar' %}">Buscar</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Inicio' %}">Inicio</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header - set the background image for the header in the line below-->
        <header class="py-5 bg-image-full" style="background-image: url('https://larepublica.pe/resizer/wexAc5QQTBEbcXcvGUyGIbUveZA=/480x282/top/smart/cloudfront-us-east-1.images.arcpublishing.com/gruporepublica/OXVY4JGEBJHWNJUCOZE4R5OZXA.png');
        width: 100%;
        height: 100%;
        position: relative;">
            <div class="text-center my-1">
                <img class="img-fluid rounded-circle mb-4" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw4nwlCIwkg-ipQUYSFn6wJ9vkd9-YFyJX4FkhBDSHzR2yPwf53ZCFmiG2xlRqYbH8cz4&usqp=CAU" alt="..." />
            

                {% block titulo %}


                {% endblock %}

                <p class="text-white-50 mb-0"></p>
                
                {% block descripcion %}



                {% endblock %}

            </div>
        </header>

        {% block pie %}


        {% endblock %}
        
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Realizado por:</p></div>
            <div class="container"><p class="m-0 text-center text-white"> Bogarin, Luciano</p></div>
            <div class="container"><p class="m-0 text-center text-white"> Tumbarello, Luis</p></div>
            <div class="container"><p class="m-0 text-center text-white"> Giacomelli, Luis</p></div>
            <li align="center"; class="nav-item"><a class="m-0 text-center text-white" href="{% url 'Sobrenosotros' %}">About</a></li>
        </footer>   
        <!-- Core theme JS-->
        <script src="{% static 'app1/js/scripts.js' %}"></script>
    </body>
</html>

app1/templates/app1/pasajero_b.html
{% extends "app1/padre2.html" %}



{% block titulo %}

<h4>
    Esta página mostrará los pasajeros.
</h4>

{% endblock %}


{% block descripcion %}

<div>
    
    <h5>
        <p>Estás buscando los pasajeros con número de vuelo: {{busqueda_pasa}}</p>
    </h5>

    {% for pasajero in pasajeros %}

        <ul>
            <li>Nombre: {{pasajero.nombre}}</li>
            <li>Apelido: {{pasajero.apellido}}</li>
            <li>Documento: {{pasajero.documento}}</li>
            <li>Numero de vuelo: {{pasajero.id_vuelo}}</li>

            {% if request.user.is_superuser %}

            <button style="background-color:black; border-color: forestgreen">
                <em>
                    <a href="{% url 'EliminaPasajero' pasajero.id_vuelo %}"> Eliminar Pasajero</a>
                </em>
            </button>

            <button style="background-color:black; border-color: forestgreen">
                <em>
                    <a href="{% url 'EditarPasajero' pasajero.id_vuelo %}"> Editar Pasajero</a>
                </em>
            </button>

            {% else %}

            ----------------------------

            {% endif %}

        </ul>
        
    {% endfor %}

</div>

{% if request.user.is_superuser %}

<button style="background-color:black; border-color: forestgreen">
    <em>
        <a href="{% url 'Crear Pasajeros' %}"> Agregar otro Pasajero</a>
    </em>
</button>

{% else %}

{% endif %}



{% endblock %}

app1/templates/app1/personal_b.html
{% extends "app1/padre2.html" %}



{% block titulo %}

<h4>
    Esta página mostrará el personal.
</h4>

{% endblock %}


{% block descripcion %}


<div>
    <h5>
        <p>Estás buscando el personal con profesion: {{busqueda_per}}</p>
    </h5>

    {% for personal in personas %}

        <ul>
            <li>Nombre: {{personal.nombre}}</li>
            <li>Apellido: {{personal.apellido}}</li>
            <li>Profesion: {{personal.profesion}}</li>
            <li>Numero de vuelo: {{personal.id_vuelo}}</li>

            {% if request.user.is_superuser %}

            <button style="background-color:black; border-color: forestgreen">
                <em>
                    <a href="{% url 'EliminaPersonal' personal.profesion %}"> Eliminar Personal</a>
                </em>
            </button>

            <button style="background-color:black; border-color: forestgreen">
                <em>
                    <a href="{% url 'EditarPersonal' personal.profesion %}"> Editar Personal</a>
                </em>
            </button>

            {% else %}

            ----------------------------

            {% endif %}

        </ul>
        
    {% endfor %}

</div>

{% if request.user.is_superuser %}

<button style="background-color:black; border-color: forestgreen">
    <em>
        <a href="{% url 'Crear Personal' %}"> Agregar otro Personal</a>
    </em>
</button>

{% else %}

{% endif %}



{% endblock %}